// <auto-generated />
using DRB_HMI_3D.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DRB_HMI_3D.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521012308_Updatepress")]
    partial class Updatepress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DRB_HMI_3D.Models.PressGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndIndex")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StartIndex")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("PressGroups");
                });

            modelBuilder.Entity("DRB_HMI_3D.Models.PressItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("KepwareTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PressGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PressGroupId");

                    b.ToTable("PressItems");
                });

            modelBuilder.Entity("DRB_HMI_3D.Models.PressTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KepwareAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PressItemId")
                        .HasColumnType("int");

                    b.Property<short>("Value")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PressItemId");

                    b.ToTable("PressTags");
                });

            modelBuilder.Entity("DRB_HMI_3D.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("DRB_HMI_3D.Models.PressGroup", b =>
                {
                    b.HasOne("DRB_HMI_3D.Models.Workshop", "Workshop")
                        .WithMany("PressGroups")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("DRB_HMI_3D.Models.PressItem", b =>
                {
                    b.HasOne("DRB_HMI_3D.Models.PressGroup", "PressGroup")
                        .WithMany("PressItems")
                        .HasForeignKey("PressGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PressGroup");
                });

            modelBuilder.Entity("DRB_HMI_3D.Models.PressTag", b =>
                {
                    b.HasOne("DRB_HMI_3D.Models.PressItem", "PressItem")
                        .WithMany("Tags")
                        .HasForeignKey("PressItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PressItem");
                });

            modelBuilder.Entity("DRB_HMI_3D.Models.PressGroup", b =>
                {
                    b.Navigation("PressItems");
                });

            modelBuilder.Entity("DRB_HMI_3D.Models.PressItem", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("DRB_HMI_3D.Models.Workshop", b =>
                {
                    b.Navigation("PressGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
